---
title: "Calm by doing?"
author: "Daniel Nicola"
date: '2022-04-01'
categories: ["Random Stuff"]
tags: []
---

This 'advice' could be helpful for some, some others might not like it at all. 

A while ago I was looking for ways to relax and calm my mind. Ended up finding some reading material, a podcast and one or two videos that did not relax me at all but instead, got me into the path of feeling fulfilled and seeing things in a different way. To be honest, it made me cut the bullshit and think as I used to when I was a kid, realizing a lot of stuff is way simpler than it seems.

So if you want the advice, you can go [here](https://garyjohnbishop.com/) and check out Gary's shit. I mean the books and talks (you will enjoy his mix of accents). I myself started with 'Unf*ck yourself', and honestly, it was a slap that woke me up to a new world. I read it in no time and ordered a couple more of his books. _Just to be clear, I don't get commission or anything, I'm pretty sure this guy doesn't even know I exist._

Not a reading fan? The guy has a podcast in spotify and a bunch of other platforms, it's called _Unfuck Nation with Gary John Bishop_. You get a bit of soft words about different topics every time and his advice for people that reach out with problems/challenges/situations...

So there you go, a little advice on where to get 'advice'. It helped me start moving and doing, discovering and living. I even write this *super helpful* kind of blog posts now. Oh and to cover the whole title, I feel more calm now :D.