---
title: "R en Paralelo (la manera tradicional)"
author: "Daniel Nicola"
date: '2022-06-02'
categories: ["R Posts", "R en Español"]
tags: ["R"]
---

La librería `parallel` ha estado activa desde hace varios años y ha sido muy poco utilizada por personas como yo. Esta no es la única manera de realizar cálculos en paralelo en `R` pero es quizá la más tradicional y la manera en que se la utiliza es similar a otras librerías/paquetes. Simplemente se deben seguir 3 pasos (descritos líneas abajo). Esta vez, he utilizado solamente `apply` y `parApply` pero claro, puedes hacer un montón de aplicaciones en paralelo. Si estás interesado en realizar más cosas en paralelo, puedes echar un ojo a `doParallel` y `foreach` para construir loops y correrlos en más de un core. Una librería más reciente es `future` que la puedes encontrar [aquí](https://futureverse.org). Si utilizas el `tidyverse`, en especial la librería `purrr` se te hará fácil trabajar con `furrr`.

Si estás interesada/o en entrenar modelos en paralelo, quizá es bueno saber que la computación en paralelo viene integrada a varios paquetes/librerías que se utilizan para esto. Por ejemplo, si trabajas con `tidymodels` una línea de código `doParallel::registerDoParallel()` antes de hacer el tuning de un grid (`tune_grid(...)`) es suficiente para que trabajen varios cores en lugar de uno sólo, ahorrándote tiempo significativamente.

# R en Paralelo
- Crea un cluster
- Corre un código
- Detienes el cluster

Un ejemplo básico de uso de `R` en paralelo está en este video:
<div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;">
  <iframe src="https://www.youtube.com/embed/fhsFdXEy-YA" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen="" title="YouTube Video"></iframe>

</div>
El código les dejo aquí. Topes!

```{r}
library(parallel)
library(tidyverse)

#DATOS
data <- matrix(rnorm(100000*20, 1000, 500), nrow = 100000, ncol = 20) %>%
  as.data.frame() %>%
  rename_all(function(x) paste0("col_", 1:20))

num_cores <- detectCores()

#Crear cluster
cl <- makeCluster(num_cores-1)

#Código normal
system.time(apply(data, 2, mean))


#Código en paralelo
system.time(parApply(cl, data, 2, mean))

#Detener el cluster
stopCluster(cl)
```







