---
title: "Control de Versiones con RStudio"
author: "Daniel Nicola"
date: '2022-03-11'
categories: ["R Posts", "R en Español"]
tags: ["R Markdown", "R", "Data Science", "Git"]
---

En mi colegio (o secundaria), teníamos un cura como rector que decía: "el que controla su lengua, es varón perfecto". Cambiemos a: "el que controla sus versiones, es buen coder mi brother". También podríamos decir: "deja de hablar huevadas"... pero bueno, al tema. El control de versiones acolita, acolita un montón, sin importar el tipo de archivo con el que trabajes. Puedes olvidarte de: tesis_v1, tesis_v2,....tesis_final, tesis_final_final, tesis_la_vencida, ...tesis_final_final_final_imprimir...

Con el control de versiones puedes mirar cada cambio en tu archivo o archivos uno a uno, puedes regresar a una versión anterior, tener varias branches y además, quizá más importante, cambios que otros hagan cuando estás colaborando en un proyecto. Para muchos de los que leen esto (de todos los 3 o 4 lectores de mi blog) esta info es conocida, pero si estás comenzando con Data Science, o si lo has hecho durante mucho tiempo pero sin utilizar GIT, esto podrá cambiar tu vida más que herbalife (ja...ja ...).

Grabé otro video, sobre como instalar GIT y configurarlo en RStudio:

<div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;">
  <iframe src="https://www.youtube.com/embed/rdHN7EQP_8Y" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen="" title="YouTube Video"></iframe>

</div>

Si estás interesado puedes empezar tu cuenta en [GitHub](https://github.com) y tener tus propios repositorios. También puedes mirar las cuentas de otra gente, copiar, colaborar y mejorar códigos en un **caganal** de lenguajes.
Otra plataforma que puedes mirar: [Bitbucket](https://bitbucket.org/), quizá sea mejor, según tu uso. 

Topes!
